### ISSUE TITLE
Very minor correction for README

### ISSUE THREAD

**Issue by RYFN** [openraildata/stomp-client-python#4]
> set the USERNAME, PASSWORD and HOSTNAME variables to the values shown in 'Username', 'Password' and 'Live Feed Topic'

Should read

> ... to the values shown in 'Username', 'Password' and 'Messaging host'

**Comment by codebox** [comment]
also the port number may have to be changed, the default 61618 was incorrect and I had to change it to the value shown in My Feeds which was 61613

**Comment by poggs** [comment]
Can you submit a pull request with these changes?

**Comment by codebox** [comment]
done
