### ISSUE TITLE
Does not work with Stomp V5

### ISSUE THREAD

**Issue by wyatt** [openraildata/stomp-client-python#9]
I was encountering an issue, similar to that of this user: https://groups.google.com/g/openraildata-talk/c/NBoY1-zycyI/m/-qDV1NMaCAAJ, where I would get an immediate disconnection.

Downgrading to stomp.py<5 seemed to fix the issue.

**Comment by poggs** [comment]
I've recently updated the code to require stomp.py>=8.0.0, which fixes this issue
